name: ASP.NET Core CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Change if you're using a different version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      # Debug Build
      - name: Debug Build
        run: dotnet build --configuration Release --no-restore || exit 1

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      # Debug Publish
      - name: Debug Publish
        run: dotnet publish -c Release -o ./publish || exit 1

      # List published files
      - name: List Files After Publish
        run: ls -R ./publish || exit 1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish
